[default]   # Optional for local defaults
address = "127.0.0.1"
port = 8000

[release]   # This is what Render will use
address = "0.0.0.0"  # listen on all interfaces
port = ${PORT}        # use the environment variable Render sets